# -*- coding: utf-8 -*-
"""genreprediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGxaG5BZVQgfdDTgHqNLJjdZO570hLTV
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree

music_data= pd.read_csv('music.csv')
music_data

X=music_data.drop(columns=['genre'])
X

y = music_data['genre']
y

X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

model=DecisionTreeClassifier()
model.fit(X_train,y_train)
predictions=model.predict(X_test)
score=accuracy_score(y_test, predictions)
score

tree.export_graphviz(model, out_file='music-recommender.dot',
                    feature_names=['age','gender'],
                    class_names=sorted(y.unique()),
                    label='all',
                    rounded=True,
                    filled=True)